plugins {
    id 'java-library'
    id 'maven-publish'
}

base {
    archivesName = "${modId}-${project.name}-${minecraftVersion}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version as int)
    withSourcesJar()
}

repositories {
    mavenCentral()
    maven { url "https://maven.neoforged.net/releases/" }
    maven { url "https://maven.fabricmc.net/" }
    exclusiveContent {
        forRepository {
            maven {
                name = 'CurseForge'
                url = 'https://cursemaven.com'
            }
        }
        filter { includeGroup 'curse.maven' }
    }
}

['apiElements', 'runtimeElements', 'sourcesElements'].each { variant ->
    configurations."$variant".outgoing {
        capability("$group:${base.archivesName.get()}:$version")
        capability("$group:$modId-${project.name}-${minecraftVersion}:$version")
        capability("$group:$modId:$version")
    }
    publishing.publications.configureEach {
        suppressPomMetadataWarningsFor(variant)
    }
}

sourcesJar {
    from(rootProject.file('LICENSE')) {
        rename { "${it}_${modName}" }
    }
}

jar {
    from(rootProject.file('LICENSE')) {
        rename { "${it}_${modName}" }
    }
    manifest {
        attributes([
            'Specification-Title'   : modName,
            'Specification-Vendor'  : 'FinnDog',
            'Specification-Version' : project.jar.archiveVersion,
            'Implementation-Title'  : project.name,
            'Implementation-Version': project.jar.archiveVersion,
            'Implementation-Vendor' : 'FinnDog',
            'Built-On-Minecraft'    : minecraftVersion
        ])
    }
}

processResources {
    var expandProps = [
        'version'                    : version,
        'mod_name'                   : modName,
        'mc_version'                 : minecraftVersion,
        'mod_id'                     : modId,
        'mod_description'            : modDescription,
        'mod_homepage'               : modHomepage,
        'mod_sources'                : modSources,
        'mod_issues'                 : modIssues,
        'mod_discord'                : modDiscord,
        'mod_kofi'                   : modKofi,
        'mod_curseforge'             : modCurseforge,
        'mod_modrinth'               : modModrinth,
        'mod_releases'               : modReleases,
        'structure_lib_version_range': structureLibVersionRange,
        'fabric_version'             : fabric_version,
        'fabric_loader_version'      : fabric_loader_version,
        'neoforge_loader_version_range': neoforge_loader_version_range,
        'forge_loader_version_range' : forge_loader_version_range,
        'minecraft_version_range'    : minecraft_version_range
    ]
    filesMatching(['fabric.mod.json', 'quilt.mod.json', 'META-INF/*.toml', 'pack.mcmeta', '*.mixins.json']) {
        expand expandProps
    }
    inputs.properties(expandProps)
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }
    repositories {
        if (System.getenv('local_maven_url')) {
            maven {
                url System.getenv('local_maven_url')
            }
        }
    }
}
