org.gradle.jvmargs=-Xmx2G
modName=MoogsVoyagerStructuresIntegrated
minecraftVersion=1.20
modVersion=5.0.7
modId=mvsintegrated
modDescription=160+ structures made with vanilla blocks and entities bringing life to your world! Discover loot, enemies, & villagers along the way!
modHomepage=https://www.curseforge.com/minecraft/mc-mods/moogs-voyager-structures
modSources=https://github.com/Moog-s-Mods/MoogsVoyagerStructures
modReleases=https://github.com/finnsetchell/MoogsVoyagerStructures-Integrated/releases
modIssues=https://github.com/Moog-s-Mods/MoogsVoyagerStructures/issues
modDiscord=https://discord.gg/S5nffJbuvA
modKofi=https://ko-fi.com/finndog
modCurseforge=https://www.curseforge.com/minecraft/mc-mods/moogs-voyager-structures-integrated
modModrinth=https://modrinth.com/mod/moogs-voyager-structures-integrated

# Structure Lib dependency range (forge mods.toml)
structureLibVersionRange=[1.0.0,)

# Publishing display customization
publishDisplayPrefix=MVSI
publishDisplaySuffix=[UNIVERSAL]

# Publishing platform settings
modrinthProjectId=cbWB9PF5
curseforgeProjectId=1542803
curseforgeProjectSlug=mvsi-moogs-voyager-structures-integrated
modrinthProjectSlug=mvsi-moogs-voyager-structures-integrated
publishMcStart=1.20
publishMcEnd=1.20.6
releaseType=minor

# Discord webhook settings
discordAvatarUrl=https://media.forgecdn.net/avatars/thumbnails/869/885/64/64/638285724433169131.png
discordEmbedColor=#1A6E8A
discordThumbnailUrl=https://www.bisecthosting.com/images/CF/MVS/BH_NU_HEADER.png
discordRoleId=1466012771379581039
discordPing=false
