modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="GNU Lesser General Public License v3.0"
issueTrackerURL="${mod_issues}"
showAsResourcePack=false

[[mods]]
    modId="${mod_id}"
    logoFile="assets/mvsintegrated/icon.png"
    logoBlur=false
    version="${version}"
    displayName="${mod_name}"
    displayURL="${mod_homepage}"
    authors="FinnDog"
    credits="Built by Phantax and AlmdudlerKing"
    description='''${mod_description}'''

[[dependencies.mvsintegrated]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_loader_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mvsintegrated]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.21.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mvsintegrated]]
    modId="moogs_structures"
    type="required"
    versionRange="${structure_lib_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mvsintegrated]]
    modId="mvs"
    type="required"
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.mvsintegrated]]
    modId="supplementaries"
    type="optional"
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mvsintegrated]]
    modId="amendments"
    type="optional"
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"
