name: Validate

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags-ignore: ['*.*.*-*', '*.*.*-alpha.*-*']

jobs:
  validate:
    name: Validate Structures
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mod project
        uses: actions/checkout@v6

      - name: Run NBT check
        run: |
          pip install nbtlib
          python scripts/nbt_check.py
